In [1]:
import pandas as pd

df = pd.read_csv("../data/dataset1.csv")
df.head()

,id,listing_id,url,source,residential_complex_id,residential_complex_name,rooms,area,living_area,kitchen_area,...,internet,documents,offer_type,address,district,latitude,longitude,parsed_at,updated_at,is_active
0,1,691048362,https://krisha.kz/a/show/691048362?srchid=019b...,krisha.kz,NaN,Respublika,2,72.50,NaN,NaN,...,NaN,NaN,NaN,Е-36 5,Нура р-н,51.128205,71.385412,2026-01-03T20:50:46.421397,NaN,1
1,2,1004599137,https://krisha.kz/a/show/1004599137?srchid=019...,krisha.kz,NaN,Family Town,3,89.30,NaN,11.80,...,NaN,NaN,NaN,Е652 6,Есильский р-н,51.059035,71.420952,2026-01-03T20:50:52.735945,NaN,1
2,3,761512600,https://krisha.kz/a/show/761512600?srchid=019b...,krisha.kz,NaN,Свечки,2,72.10,NaN,NaN,...,NaN,NaN,NaN,Богенбай батыра 30,Сарыарка р-н,51.189164,71.356273,2026-01-03T20:51:01.431439,NaN,1
3,4,1007029481,https://krisha.kz/a/show/1007029481?srchid=019...,krisha.kz,NaN,Sezim Qala.Baqyt,4,106.77,NaN,11.13,...,NaN,NaN,NaN,Туран 55/12,Нура р-н,51.114484,71.393405,2026-01-03T20:51:09.278359,NaN,1
4,5,697845378,https://krisha.kz/a/show/697845378?srchid=019b...,krisha.kz,NaN,Boston Comfort House,2,39.00,NaN,NaN,...,NaN,NaN,NaN,"мкр Уркер, Кургальжинское шоссе 108",Нура р-н,51.121439,71.283095,2026-01-03T20:51:19.144336,NaN,1

In [2]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 18388 entries, 0 to 18387
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        18388 non-null  int64
 1   listing_id                18388 non-null  int64
 2   url                       18388 non-null  str
 3   source                    18388 non-null  str
 4   residential_complex_id    0 non-null      float64
 5   residential_complex_name  14495 non-null  str
 6   rooms                     18388 non-null  int64
 7   area                      18388 non-null  float64
 8   living_area               82 non-null     float64
 9   kitchen_area              7621 non-null   float64
 10  floor                     17417 non-null  float64
 11  total_floors              17417 non-null  float64
 12  price_usd                 18388 non-null  int64
 13  price_local               18388 non-null  int64
 14  price_per_m2              18388 non-null  int64
 15  house_type                17271 non-null  str
 16  year_built                18388 non-null  int64
 17  building_series           0 non-null      float64
 18  ceiling_height            15189 non-null  float64
 19  condition                 7501 non-null   str
 20  bathroom                  11224 non-null  str
 21  balcony                   9407 non-null   str
 22  parking                   12651 non-null  str
 23  furniture                 9065 non-null   str
 24  floor_type                7887 non-null   str
 25  heating                   0 non-null      float64
 26  security                  8245 non-null   str
 27  internet                  0 non-null      float64
 28  documents                 0 non-null      float64
 29  offer_type                0 non-null      float64
 30  address                   18388 non-null  str
 31  district                  17610 non-null  str
 32  latitude                  18388 non-null  float64
 33  longitude                 18388 non-null  float64
 34  parsed_at                 18388 non-null  str
 35  updated_at                3550 non-null   str
 36  is_active                 18388 non-null  int64
dtypes: float64(14), int64(8), str(15)
memory usage: 5.2 MB

,id,listing_id,residential_complex_id,rooms,area,living_area,kitchen_area,floor,total_floors,price_usd,...,year_built,building_series,ceiling_height,heating,internet,documents,offer_type,latitude,longitude,is_active
count,18388.000000,1.838800e+04,0.0,18388.000000,18388.000000,82.000000,7621.000000,17417.000000,17417.000000,1.838800e+04,...,18388.000000,0.0,15189.000000,0.0,0.0,0.0,0.0,18388.000000,18388.000000,18388.0
mean,9194.500000,9.725041e+08,NaN,2.317762,73.047921,71.270122,13.122130,6.767526,11.561750,9.395154e+04,...,2016.711225,NaN,2.896558,NaN,NaN,NaN,NaN,51.124212,71.426141,1.0
std,5308.302711,1.005727e+08,NaN,1.041853,41.691703,43.650309,10.682632,4.329900,5.109851,8.081485e+04,...,11.192800,NaN,0.610195,NaN,NaN,NaN,NaN,0.204731,0.334562,0.0
min,1.000000,1.940254e+07,NaN,1.000000,10.800000,18.800000,1.200000,1.000000,2.000000,7.840000e+03,...,1950.000000,NaN,2.000000,NaN,NaN,NaN,NaN,42.346735,51.905115,1.0
25%,4597.750000,1.005556e+09,NaN,2.000000,43.700000,41.625000,10.000000,3.000000,9.000000,5.010700e+04,...,2013.000000,NaN,2.700000,NaN,NaN,NaN,NaN,51.111286,71.391065,1.0
50%,9194.500000,1.007650e+09,NaN,2.000000,63.000000,60.000000,12.000000,6.000000,10.000000,7.073900e+04,...,2020.000000,NaN,3.000000,NaN,NaN,NaN,NaN,51.127912,71.426501,1.0
75%,13791.250000,1.008192e+09,NaN,3.000000,90.000000,86.000000,15.000000,9.000000,14.000000,1.080740e+05,...,2024.000000,NaN,3.000000,NaN,NaN,NaN,NaN,51.148870,71.468840,1.0
max,18388.000000,1.008408e+09,NaN,13.000000,556.400000,285.200000,707.000000,41.000000,43.000000,2.947475e+06,...,2028.000000,NaN,28.000000,NaN,NaN,NaN,NaN,55.231707,81.102141,1.0

In [3]:

use_cols = [
    "rooms",
    "area",
    "floor",
    "total_floors",
    "year_built",
    "house_type",
    "condition",
    "ceiling_height",
    "price_local"
]

In [4]:
df = df[use_cols]

In [5]:
df = df.dropna(subset=["price_local", "area", "rooms"])

In [6]:
df = df[
    (df["area"] >= 15) & (df["area"] <= 300) &
    (df["price_local"] >= 1_000_000) &
    (df["price_local"] <= 300_000_000)
]

In [7]:
df["floor"] = df["floor"].fillna(df["floor"].median())
df["total_floors"] = df["total_floors"].fillna(df["total_floors"].median())
df["ceiling_height"] = df["ceiling_height"].fillna(df["ceiling_height"].median())

df["house_type"] = df["house_type"].fillna("unknown")
df["condition"] = df["condition"].fillna("unknown")

In [8]:
df["house_age"] = 2025 - df["year_built"]
df = df.drop(columns=["year_built"])

In [9]:
df.info()
df.head()

<class 'pandas.DataFrame'>
Index: 18280 entries, 0 to 18387
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   rooms           18280 non-null  int64
 1   area            18280 non-null  float64
 2   floor           18280 non-null  float64
 3   total_floors    18280 non-null  float64
 4   house_type      18280 non-null  str
 5   condition       18280 non-null  str
 6   ceiling_height  18280 non-null  float64
 7   price_local     18280 non-null  int64
 8   house_age       18280 non-null  int64
dtypes: float64(4), int64(3), str(2)
memory usage: 1.4 MB

,rooms,area,floor,total_floors,house_type,condition,ceiling_height,price_local,house_age
0,2,72.50,6.0,10.0,монолитный,unknown,3.0,38497500,2
1,3,89.30,4.0,5.0,кирпичный,unknown,2.8,45000000,11
2,2,72.10,6.0,10.0,монолитный,"не новый, но аккуратный ремонт",2.7,29000000,27
3,4,106.77,8.0,9.0,монолитный,unknown,3.0,76000000,2
4,2,39.00,2.0,2.0,кирпичный,unknown,2.7,14000000,4

In [10]:
X = df.drop(columns=["price_local"])
y = df["price_local"]

In [11]:
num_cols = [
    "area",
    "rooms",
    "floor",
    "total_floors",
    "ceiling_height",
    "house_age"
]

cat_cols = [
    "house_type",
    "condition"
]

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", num_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
    ]
)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [14]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=300, max_depth=18, random_state=42, n_jobs=-1)

In [15]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", model)
])

In [16]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['area', 'rooms', 'floor',
                                                   'total_floors',
                                                   'ceiling_height',
                                                   'house_age']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['house_type',
                                                   'condition'])])),
                ('model',
                 RandomForestRegressor(max_depth=18, n_estimators=300,
                                       n_jobs=-1, random_state=42))])

In [17]:
from sklearn.metrics import mean_absolute_error, r2_score

preds = pipeline.predict(X_test)
print("MAE:", mean_absolute_error(y_test, preds))
print("R2:", r2_score(y_test, preds))

MAE: 7348946.458973772
R2: 0.8422436936538369

In [18]:
import joblib
joblib.dump(pipeline, "../model/price_pipeline.joblib")

['../model/price_pipeline.joblib']